language: node_js
node_js:
  - node
script:
  - yarn install
  - yarn build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: "cloudscale-rancher-v2-ui-driver"
  acl: public-read
  skip_cleanup: true
  local-dir: dist
  on:
    branch: master
