language: node_js
node_js:
  - node
script:
  - yarn install
  - yarn build
deploy:
  provider: s3
  endpoint: https://objects.cloudscale.ch
  access_key_id: $CLOUDSCALE_OBJECTS_ACCESS_KEY
  secret_access_key: $CLOUDSCALE_OBJECTS_SECRET_KEY
  bucket: $CLOUDSCALE_OBJECTS_BUCKET
  acl: public-read
  skip_cleanup: true
  local-dir: dist
  on:
    branch: master
