on:
  push:
    branches:
      - master
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      # Install aws cli, it's not present in act medium image. Use --update to make idempotent on GitHub.
      - run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install --update
      - env:
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDSCALE_OBJECTS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDSCALE_OBJECTS_SECRET_KEY }}
          BUCKET: ${{ secrets.CLOUDSCALE_OBJECTS_BUCKET }}
          REGION: ${{ secrets.REGION }}
        run: aws s3 sync ./dist/ s3://${{ env.BUCKET }} --delete --acl public-read --endpoint=https://objects.${{ env.REGION }}.cloudscale.ch --region ${{ env.REGION }}


